app/models/quiz.py
from app import db
from datetime import datetime

class Quiz(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

    # Questões 1-4
    question_1 = db.Column(db.Time, nullable=False)
    question_2 = db.Column(db.Integer, nullable=False)
    question_3 = db.Column(db.Time, nullable=False)
    question_4 = db.Column(db.Float, nullable=False)

    # Questão 5 (a-j)
    question_5_a = db.Column(db.Integer, nullable=False)
    question_5_b = db.Column(db.Integer, nullable=False)
    question_5_c = db.Column(db.Integer, nullable=False)
    question_5_d = db.Column(db.Integer, nullable=False)
    question_5_e = db.Column(db.Integer, nullable=False)
    question_5_f = db.Column(db.Integer, nullable=False)
    question_5_g = db.Column(db.Integer, nullable=False)
    question_5_h = db.Column(db.Integer, nullable=False)
    question_5_i = db.Column(db.Integer, nullable=False)
    question_5_j = db.Column(db.Integer, nullable=False)
    question_5_j_other = db.Column(db.String(200))

    # Questões 6-10
    question_6 = db.Column(db.Integer, nullable=False)
    question_7 = db.Column(db.Integer, nullable=False)
    question_8 = db.Column(db.Integer, nullable=False)
    question_9 = db.Column(db.Integer, nullable=False)
    question_10 = db.Column(db.Integer, nullable=False)

    # Resultado do PSQI
    subjective_sleep_quality = db.Column(db.Integer, nullable=True)
    sleep_latency = db.Column(db.Integer, nullable=True)
    sleep_duration = db.Column(db.Integer, nullable=True)
    habitual_sleep_efficiency = db.Column(db.Integer, nullable=True)
    sleep_disorders = db.Column(db.Integer, nullable=True)
    use_of_sleeping_pills = db.Column(db.Integer, nullable=True)
    daytime_dysfunction = db.Column(db.Integer, nullable=True)
    overall_score = db.Column(db.Integer, nullable=True)


    # Relacionamento com o usuário
    user = db.relationship('User', back_populates='quizzes')

    def __repr__(self):
        return f'<Quiz {self.id} for User {self.user_id}>'

app/controllers/quiz_controller.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from app import db
from flask_login import login_required, current_user
from app.models.user import User
from app.models.quiz import Quiz as QuizModel
from datetime import datetime, time, timedelta
from wtforms import Form, StringField, IntegerField, DateField, TimeField, FloatField, RadioField, validators
from wtforms.validators import DataRequired, NumberRange, Optional, Length, InputRequired
from sqlalchemy import asc
from sqlalchemy import func

bp = Blueprint('quiz', __name__)

class Quiz(Form):
    question_1 = TimeField('Questão 1', [validators.DataRequired()])
    question_2 = IntegerField('Questão 2', [validators.DataRequired(), validators.NumberRange(min=0)])
    question_3 = TimeField('Questão 3', [validators.DataRequired()])
    question_4 = FloatField('Questão 4', [validators.DataRequired(), validators.NumberRange(min=0, max=24)])
    question_5_a = RadioField('Questão 5a', choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], validators=[InputRequired()])
    question_5_b = RadioField('Questão 5b', choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], validators=[InputRequired()])
    question_5_c = RadioField('Questão 5c', choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], validators=[InputRequired()])
    question_5_d = RadioField('Questão 5d', choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], validators=[InputRequired()])
    question_5_e = RadioField('Questão 5e', choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], validators=[InputRequired()])
    question_5_f = RadioField('Questão 5f', choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], validators=[InputRequired()])
    question_5_g = RadioField('Questão 5g', choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], validators=[InputRequired()])
    question_5_h = RadioField('Questão 5h', choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], validators=[InputRequired()])
    question_5_i = RadioField('Questão 5i', choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], validators=[InputRequired()])
    question_5_j_other = StringField('Questão 5j Outro', [Optional(), Length(max=200)])
    question_5_j = RadioField('Questão 5j', choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], validators=[InputRequired()])
    question_6 = RadioField('Questão 6', choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], validators=[InputRequired()])
    question_7 = RadioField('Questão 7', choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], validators=[InputRequired()])
    question_8 = RadioField('Questão 8', choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], validators=[InputRequired()])
    question_9 = RadioField('Questão 9', choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], validators=[InputRequired()])
    question_10 = RadioField('Questão 10', choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], validators=[InputRequired()])


@bp.route('/', methods=['GET'])
@login_required
def index():
    quizzes = QuizModel.query.filter_by(user_id=current_user.id).order_by(asc(QuizModel.created_at)).all()

    chart_data = {
        'labels': [],
        'scores': []
    }
    for quiz in quizzes:
        chart_data['labels'].append(quiz.created_at.strftime('%d/%m/%Y'))
        chart_data['scores'].append(quiz.overall_score)

    min_score = db.session.query(
            QuizModel.id,
            QuizModel.overall_score,
            QuizModel.created_at
        ).filter(
            QuizModel.user_id == current_user.id
        ).order_by(
            QuizModel.overall_score.asc(),
            QuizModel.created_at.asc()
        ).first()

    max_score = db.session.query(
        QuizModel.id,
            QuizModel.overall_score,
            QuizModel.created_at
        ).filter(
            QuizModel.user_id == current_user.id
        ).order_by(
            QuizModel.overall_score.desc(),
            QuizModel.created_at.desc()
        ).first()


    return render_template('quiz/index.html', quizzes=quizzes, title="Seus questionários", chart_data=chart_data, min_score=min_score, max_score=max_score)

@bp.route('/quiz', methods=['GET'])
@login_required
def quiz():
    title="ÍNDICE DA QUALIDADE DO SONO DE PITTSBURGH – (PSQI-BR)"
    return render_template('quiz/quiz.html', title=title)


@bp.route('/quiz', methods=['POST'])
@login_required
def create_quiz():
    form = Quiz(request.form)

    if form.validate():

        subjective_sleep_quality = int(form.question_6.data)
        sleep_latency = 0
        if int(form.question_2.data) <= 15:
            sleep_latency = 0
        elif int(form.question_2.data) > 15 and int(form.question_2.data) <= 30:
            sleep_latency = 1
        elif int(form.question_2.data) > 30 and int(form.question_2.data) <= 60:
            sleep_latency = 2
        else:
            sleep_latency = 3

        sleep_latency += int(form.question_5_a.data)

        if sleep_latency >= 1 and sleep_latency < 3:
            sleep_latency = 1
        elif sleep_latency >= 3 and sleep_latency < 5:
            sleep_latency = 2
        elif sleep_latency >= 5 and sleep_latency < 7:
            sleep_latency = 3
        else:
            sleep_latency = 0

        sleep_duration = 0
        if float(form.question_4.data) > 7:
            sleep_duration = 0
        elif float(form.question_4.data) >= 6 and float(form.question_4.data) <= 7:
            sleep_duration = 1
        elif float(form.question_4.data) >= 5 and float(form.question_4.data) < 6:
            sleep_duration = 2
        else:
            sleep_duration = 3

        dt1 = datetime.combine(datetime.min, form.question_1.data)
        dt2 = datetime.combine(datetime.min, form.question_3.data)
        time_diff = dt2 - dt1

        if time_diff.days < 0:
            time_diff = timedelta(days=1) + time_diff

        hours_in_bed = round(time_diff.total_seconds() / 3600, 2)
        habitual_sleep_efficiency = (float(form.question_4.data) / hours_in_bed) * 100

        if habitual_sleep_efficiency >= 85:
            habitual_sleep_efficiency = 0
        elif habitual_sleep_efficiency < 85 and habitual_sleep_efficiency >= 75:
            habitual_sleep_efficiency = 1
        elif habitual_sleep_efficiency < 75 and habitual_sleep_efficiency >= 65:
            habitual_sleep_efficiency = 2
        elif habitual_sleep_efficiency < 65:
            habitual_sleep_efficiency = 3

        sleep_disorders = int(form.question_5_b.data) + int(form.question_5_c.data) + int(form.question_5_d.data) + int(form.question_5_e.data) + int(form.question_5_f.data) + int(form.question_5_g.data) + int(form.question_5_h.data) + int(form.question_5_i.data) + int(form.question_5_j.data)

        if sleep_disorders >= 1 and sleep_disorders < 10:
            sleep_disorders = 1
        elif sleep_disorders >= 10 and sleep_disorders < 19:
            sleep_disorders = 2
        elif sleep_disorders >= 19 and sleep_disorders < 28:
            sleep_disorders = 3
        else:
            sleep_disorders = 0

        use_of_sleeping_pills = int(form.question_7.data)

        daytime_dysfunction = int(form.question_8.data) + int(form.question_9.data)

        if daytime_dysfunction >= 1 and daytime_dysfunction < 3:
            daytime_dysfunction = 1
        elif daytime_dysfunction >= 3 and daytime_dysfunction < 5:
            daytime_dysfunction = 2
        elif daytime_dysfunction >= 5 and daytime_dysfunction < 7:
            daytime_dysfunction = 3
        else:
            daytime_dysfunction = 0


        overall_score = subjective_sleep_quality + sleep_latency + sleep_duration + habitual_sleep_efficiency + sleep_disorders + use_of_sleeping_pills + daytime_dysfunction

        try:
            new_quiz = QuizModel(
                user_id=current_user.id,
                question_1=form.question_1.data,
                question_2=form.question_2.data,
                question_3=form.question_3.data,
                question_4=form.question_4.data,
                question_5_a=form.question_5_a.data,
                question_5_b=form.question_5_b.data,
                question_5_c=form.question_5_c.data,
                question_5_d=form.question_5_d.data,
                question_5_e=form.question_5_e.data,
                question_5_f=form.question_5_f.data,
                question_5_g=form.question_5_g.data,
                question_5_h=form.question_5_h.data,
                question_5_i=form.question_5_i.data,
                question_5_j=form.question_5_j.data,
                question_5_j_other=form.question_5_j_other.data,
                question_6=form.question_6.data,
                question_7=form.question_7.data,
                question_8=form.question_8.data,
                question_9=form.question_9.data,
                question_10=form.question_10.data,
                subjective_sleep_quality=subjective_sleep_quality,
                sleep_latency=sleep_latency,
                sleep_duration=sleep_duration,
                habitual_sleep_efficiency=habitual_sleep_efficiency,
                sleep_disorders=sleep_disorders,
                use_of_sleeping_pills=use_of_sleeping_pills,
                daytime_dysfunction=daytime_dysfunction,
                overall_score=overall_score
            )

            db.session.add(new_quiz)
            db.session.commit()

            flash('Quiz salvo com sucesso!', 'success')
            return redirect(url_for('quiz.get_quiz', id=new_quiz.id))
        except Exception as e:
            db.session.rollback()
            flash(f'Erro ao salvar o quiz: {str(e)}', 'error')
    if form.errors:
        for field, errors in form.errors.items():
            for error in errors:

app/templates/quiz/index.html
{% extends "layout/base_app.html" %}

{% block content %}

{% if min_score %}
<div>
    <dl class="mt-5 grid grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-3">
        <div class="relative overflow-hidden rounded-lg bg-white px-4 pb-12 pt-5 shadow sm:px-6 sm:pt-6">
            <dt>
                <div class="absolute rounded-md bg-indigo-500 p-3">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="h-6 w-6 text-white">
                        <path stroke-linecap="round" stroke-linejoin="round" d="m4.5 12.75 6 6 9-13.5" />
                    </svg>

                </div>
                <p class="ml-16 truncate text-sm font-medium text-gray-500">Menor Score</p>
            </dt>
            <dd class="ml-16 flex items-baseline pb-6 sm:pb-7">
                <p class="text-2xl font-semibold text-gray-900">{{ min_score.overall_score }}</p>
                <p class="ml-2 flex items-baseline text-sm font-semibold text-gray-600">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="h-5 w-5 flex-shrink-0 self-center text-green-500 mr-2" >
                        <path stroke-linecap="round" stroke-linejoin="round" d="M6.75 3v2.25M17.25 3v2.25M3 18.75V7.5a2.25 2.25 0 0 1 2.25-2.25h13.5A2.25 2.25 0 0 1 21 7.5v11.25m-18 0A2.25 2.25 0 0 0 5.25 21h13.5A2.25 2.25 0 0 0 21 18.75m-18 0v-7.5A2.25 2.25 0 0 1 5.25 9h13.5A2.25 2.25 0 0 1 21 11.25v7.5" />
                    </svg>
                    {{ min_score.created_at.strftime('%d/%m/%Y %H:%M') }}
                </p>
                <div class="absolute inset-x-0 bottom-0 bg-gray-50 px-4 py-4 sm:px-6">
                    <div class="text-sm">
                        <a href="{{ url_for('quiz.get_quiz', id=min_score.id) }}" class="font-medium text-indigo-600 hover:text-indigo-500">Ver questionário</a>
                    </div>
                </div>
            </dd>
        </div>
        <div class="relative overflow-hidden rounded-lg bg-white px-4 pb-12 pt-5 shadow sm:px-6 sm:pt-6">
            <dt>
                <div class="absolute rounded-md bg-indigo-500 p-3">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="h-6 w-6 text-white">
                        <path stroke-linecap="round" stroke-linejoin="round" d="m4.5 12.75 6 6 9-13.5" />
                    </svg>

                </div>
                <p class="ml-16 truncate text-sm font-medium text-gray-500">Maior Score</p>
            </dt>
            <dd class="ml-16 flex items-baseline pb-6 sm:pb-7">
                <p class="text-2xl font-semibold text-gray-900">{{ max_score.overall_score }}</p>
                <p class="ml-2 flex items-baseline text-sm font-semibold text-gray-600">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="h-5 w-5 flex-shrink-0 self-center text-green-500 mr-2" >
                        <path stroke-linecap="round" stroke-linejoin="round" d="M6.75 3v2.25M17.25 3v2.25M3 18.75V7.5a2.25 2.25 0 0 1 2.25-2.25h13.5A2.25 2.25 0 0 1 21 7.5v11.25m-18 0A2.25 2.25 0 0 0 5.25 21h13.5A2.25 2.25 0 0 0 21 18.75m-18 0v-7.5A2.25 2.25 0 0 1 5.25 9h13.5A2.25 2.25 0 0 1 21 11.25v7.5" />
                    </svg>
                    {{ max_score.created_at.strftime('%d/%m/%Y %H:%M') }}
                </p>
                <div class="absolute inset-x-0 bottom-0 bg-gray-50 px-4 py-4 sm:px-6">
                    <div class="text-sm">
                        <a href="{{ url_for('quiz.get_quiz', id=max_score.id) }}" class="font-medium text-indigo-600 hover:text-indigo-500">Ver questionário</a>
                    </div>
                </div>
            </dd>
        </div>
    </dl>
</div>

<div class="rounded-lg bg-white px-4 pb-12 pt-5 shadow sm:px-6 sm:pt-6 mt-16">
    <canvas id="scoreChart" width="400" height="200"></canvas>
</div>
{% endif %}

<div class="sm:flex sm:items-center mt-16">
    <div class="sm:flex-auto">
        <h1 class="text-base font-semibold leading-6 text-gray-900">Todos seus questionários</h1>
        <p class="mt-2 text-sm text-gray-700">Esta listagem contém o histórico completo de questionários respondidos</p>
    </div>
    <div class="mt-4 sm:ml-16 sm:mt-0 sm:flex-none">
        <a
                href="{{ url_for('quiz.quiz') }}"
                class="block rounded-md bg-indigo-600 px-3 py-2 text-center text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">
            Responder novo questionário
        </a>
    </div>
</div>
<div class="mt-8 flow-root">
    <div class="-mx-4 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
        <div class="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8">
            <div class="overflow-hidden shadow ring-1 ring-black ring-opacity-5 sm:rounded-lg">
                <table class="min-w-full divide-y divide-gray-300">
                    <thead class="bg-gray-50">
                    <tr>
                        <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6">ID</th>
                        <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Pontuação global</th>
                        <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Data do preenchimento</th>
                        <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-6">
                            <span class="sr-only">Ver</span>
                        </th>
                    </tr>
                    </thead>
                    <tbody class="divide-y divide-gray-200 bg-white">
                    {% for quiz in quizzes %}
                    <tr>
                        <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-6">{{ quiz.id }}</td>
                        <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-6">{{ quiz.overall_score }}</td>
                        <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">{{ quiz.created_at.strftime('%d/%m/%Y %H:%M') }}</td>
                        <td class="relative whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-6">
                            <a href="{{ url_for('quiz.get_quiz', id=quiz.id) }}" class="text-indigo-600 hover:text-indigo-900">Ver</a>
                        </td>
                    </tr>
                    {% endfor %}

                    <!-- More people... -->
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>


{% if min_score %}
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script>
    var ctx = document.getElementById('scoreChart').getContext('2d');
    var scoreChart = new Chart(ctx, {
        type: 'line',
        data: {
            labels: {{ chart_data.labels | tojson }},
    datasets: [{
        label: 'Pontuação Global',
        data: {{ chart_data.scores | tojson }},
    borderColor: 'rgb(75, 192, 192)',
        tension: 0.1
    }]
    },
    options: {
        responsive: true,
            scales: {
            y: {
                beginAtZero: true,
                    suggestedMax: 21  // PSQI score máximo
            }
        }
    }
    });
</script>
{% endif %}
{% endblock %}